---

- hosts: localhost

  tasks:
  - name: INSTALL HTTPD SERVER
    yum: name=httpd state=latest
 
  - name: START THE SERVICE
    service: name=httpd state=restarted

  - name: Apache | add apache iptable rule
    command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache"

  - name: save iptables
    command: iptables-save
    sudo: true
 
  



